### ISSUE TITLE
Support more Redshift credentials type

### ISSUE THREAD

**Issue by Limess** [transferwise/pipelinewise-target-redshift#10]
## Expected

The user should be able to use STS credentials, or IAM roles to authenticate the Redshift `COPY` command. This allows more granular access control and prevents the need to mint an IAM user and tokens.

## Actual

Only AWS user credentials are accepted.

**Comment by koszti** [comment]
This has been published to PyPI pipelinewise-target-redshift-1.0.8. We'll bump it in the main PipelineWise repo as well next week.

Thanks for the contribution
